fix: eslint parser and rules error
collabo-community/blocks-assistant pull request #3
Opened 2024-04-06 11:07 UTC by tylerjusfly

**This pull request makes the following changes:**
* Fixes collabo-community/put-repo-name-where-the-issue-is-located-here#putTheIssueNumberHere 

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [ ] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

Replace this text with the testing checklist from the issue this pull request fixes.

2024-04-10 10:26 UTC, Ifycode requested changes

2024-04-10 10:26 UTC, Ifycode commented on package.json
>      "@babel/plugin-syntax-dynamic-import": "^7.8.3",
Same question as before @tylerjusfly 
Do we need to still keep all these `@babel` packages, now that we are using typescript?
> why or why not?
> https://github.com/collabo-community/create-collabo-app/pull/2#discussion_r1552399291

2024-04-10 10:52 UTC, tylerjusfly commented on package.json
>      "@babel/plugin-syntax-dynamic-import": "^7.8.3",
I don't know where we are still using them, but i will try remove them and see if everything still works. Then i will remove them completely.

2024-06-23 02:31 UTC, Ifycode commented on package.json
>      "@babel/plugin-syntax-dynamic-import": "^7.8.3",
I will be taking over this PR @tylerjusfly

2024-11-29 01:00 UTC, closed without merging